### ISSUE TITLE
Make it easy to set up an Assembler project

### ISSUE THREAD

**Issue by sebastianbergmann** [BartmanAbyss/vscode-amiga-debug#24]
Right now it is very easy and convenient to create a C/C++ project: simply press <kbd>Ctrl+Shift+P</kbd>, select `Amiga: Init Project`, and you're all set. This is awesome!

But unless I am missing something (in which case: sorry!), there is no such easy way to create an Assembler project.

**Comment by BartmanAbyss** [comment]
What exactly are you trying to do? The default project is already set up for assembly. Just delete main.c and add a .s file (if that doesn't work with the 1.0 version from the Marketplace, try downloading a 1.1 preview from the Github releases)

**Comment by sebastianbergmann** [comment]
I did that with the latest stable and now with the latest preview of 1.1: open empty directory, <kbd>Ctrl+Shift+P</kbd>, select `Amiga: Init Project`, delete `main.c`, create `main.s`, copy&paste http://coppershade.org/asmskool/Tut5.S into `main.s`, save, configure ROM in `launch.json`, and <kbd>F5</kbd>:

```
> Executing task: c:\Users\sb\.vscode\extensions\bartmanabyss.amiga-debug-1.1.0-preview21\bin\gnumake.exe -j4 <

Compiling support/gcc8_c_support.c
Assembling support/gcc8_a_support.s
Assembling support/depacker_doynax.s
Linking a.mingw.elf
c:/users/sb/.vscode/extensions/bartmanabyss.amiga-debug-1.1.0-preview21/bin/opt/bin/../lib/gcc/m68k-amiga-elf/10.1.0/../../../../m68k-amiga-elf/bin/ld.exe: obj/gcc8_c_support.o: in function `KPrintF':
C:/Users/sb/Downloads/Amiga/example/support/gcc8_c_support.c:67: undefined reference to `SysBase'
c:/users/sb/.vscode/extensions/bartmanabyss.amiga-debug-1.1.0-preview21/bin/opt/bin/../lib/gcc/m68k-amiga-elf/10.1.0/../../../../m68k-amiga-elf/bin/ld.exe: C:/Users/sb/Downloads/Amiga/example/support/gcc8_c_support.c:64: undefined reference to `SysBase'
c:/users/sb/.vscode/extensions/bartmanabyss.amiga-debug-1.1.0-preview21/bin/opt/bin/../lib/gcc/m68k-amiga-elf/10.1.0/../../../../m68k-amiga-elf/bin/ld.exe: obj/gcc8_c_support.o: in function `_start':
C:/Users/sb/Downloads/Amiga/example/support/gcc8_c_support.c:93: undefined reference to `main'
collect2.exe: error: ld returned 1 exit status 
gnumake: *** [Makefile:33: a.mingw.elf] Error 1
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command c:\Users\sb\.vscode\extensions\bartmanabyss.amiga-debug-1.1.0-preview21\bin\gnumake.exe -j4" terminated with exit code: 1.
```

This looks to me like the build script tries to compile a C program.

**Comment by BartmanAbyss** [comment]
I made this example assembler project using the source you provided.
[asm-test.zip](https://github.com/BartmanAbyss/vscode-amiga-debug/files/5008273/asm-test.zip)
But please note, that this extension does use GNU assembler which has a different syntax than the tutorials from coppershade.org, have a look at `main.s` for the changes. If that doesn't suit you, maybe try the [amiga-assembly](https://github.com/prb28/vscode-amiga-assembly) extension instead.

**Comment by sebastianbergmann** [comment]
Thank you.
